name: gradle

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  pull_request_target:
    types: [ closed ]

jobs:
  lint:
    if: ${{ github.event.pull_request.merged != true }}
    uses: heliannuuthus/integration-deploy/.github/workflows/call-gradle-lint.yml

  build:
    if: always()
    needs: lint
    uses: heliannuuthus/integration-deploy/.github/workflows/call-gradle-build.yml

  publish:
    if: ${{ always() && github.event.pull_request.merged == true }}
    needs: build
    permissions:
      contents: read
      packages: write
    uses: heliannuuthus/integration-deploy/.github/workflows/call-gradle-publish.yml
    with:
      user: ${{ github.actor }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}