on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  push:
    branches:
      - master

jobs:
  print:
    name: Input check
    runs-on: ubuntu-latest
    steps:
      - name: Checking your input
        run: |
          echo "github.event.pull_request.merged           : $MERGED_RAW"
          echo "github.event.pull_request.merged == 'true' : $MERGED_TRUE_STR"
          echo "github.event.pull_request.merged  == true  : $MERGED_TRUE_BOOL"
        env:
          MERGED_RAW: ${{ github.event.pull_request.merged }}
          MERGED_TRUE_STR: ${{ github.event.pull_request.merged == 'true' }}
          MERGED_TRUE_BOOL: ${{ github.event.pull_request.merged == true }}
            
  lint:
    if: github.event.pull_request.merged != true
    uses: heliannuuthus/integration-deploy/.github/workflows/call-gradle-lint.yml@master

  build:
    needs: lint
    uses: heliannuuthus/integration-deploy/.github/workflows/call-gradle-build.yml@master

  publish:
    if: github.event.pull_request.merged == true
    needs: build
    permissions:
      contents: read
      packages: write
    uses: heliannuuthus/integration-deploy/.github/workflows/call-gradle-publish.yml@master
    with:
      user: ${{ github.actor }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}